## Sources.
source "%val{config}/plugins/kakoune-buffers/buffers.kak"
source "%val{config}/plugins/kakoune-find/find.kak"
source "%val{config}/plugins/kakoune-phantom-selection/phantom-selection.kak"
source "%val{config}/plugins/kakoune-mark/mark.kak"
source "%val{config}/plugins/kakoune-filetree/filetree.kak"
source "%val{config}/plugins/fzf.kak/rc/fzf.kak"
# source "%val{config}/plugins/kakoune-edit-or-dir/edit-or-dir.kak"
# source "%val{config}/plugins/auto-pairs.kak/rc/auto-pairs.kak"
# source "%val{config}/plugins/kakoune-marks/marks.kak"
# source "%val{config}/plugins/kakoune-easymotion/easymotion.kak"
# source "%val{config}/plugins/kakoune-registers/registers.kak"
# source "%val{config}/plugins/volatile-highlighting.kak/rc/volatile-highlighting.kak"

# source "%val{config}/scripts/fzf.kak"
source "%val{config}/scripts/bc.kak"
source "%val{config}/scripts/colorscheme-browser.kak"

## General settings.
set global ui_options ncurses_assistant=off
set global tabstop 4
set global indentwidth 4
# set global idle_timeout 50
# set global scrolloff 1,0
# set global ui_options ncurses_status_on_top=true
set global grepcmd 'rg --column'

colorscheme github-custom

# enable kak-lsp
eval %sh{kak-lsp --kakoune -s $kak_session}
# nop %sh{ (kak-lsp -s $kak_session -vvv ) > /tmp/kak-lsp.log 2>&1 < /dev/null & }

# hook global WinCreate ^[^*]+$ %{
hook global WinCreate .* %{
    addhl window/wrap wrap
    addhl window/number-lines number-lines -hlcursor
    # addhl window/show-whitespaces show-whitespaces -tab '›' -tabpad '⋅' -lf ' ' -spc ' ' -nbsp '⍽'
    addhl window/show-whitespaces show-whitespaces -tab '›' -tabpad '⋅' -spc ' ' -nbsp '⍽'
    addhl window/show-matching show-matching
    addhl window/VisibleWords regex \b(?:FIXME|TODO|XXX)\b 0:default+rb

    # smarttab-enable
    tab-completion-enable
    show-trailing-whitespace-enable; face window TrailingWhitespace default,red
    search-highlighting-enable; face window Search default,rgb:EDF97D+bi
}

hook global WinDisplay .* info-buffers

## File types.
def filetype-hook -params 2 %{ hook global WinSetOption "filetype=(%arg{1})" %arg{2} }
def go-format-use-goimports %{ go-format -use-goimports }

filetype-hook man %{
    rmhl window/number-lines
    set window scrolloff 1000,0
}
declare-user-mode help-and-hovers
# declare-user-mode gotodef
filetype-hook go %{
    # set window aligntab true
    set window indentwidth 0
    # set window lsp_auto_highlight_references true
    lsp-auto-signature-help-enable
    go-enable-autocomplete
    alias window format go-format-use-goimports
    alias window jump-to-definition go-jump
    # set buffer lintcmd '(gometalinter | grep -v "::\w")  <'
    map global goto u '<esc>: go-jump<ret>' -docstring 'go-jump'
    # map global goto h '<esc>:go-doc-info<ret>' -docstring 'go-doc-info'
    # map global goto l '<esc>:lsp-hover<ret>' -docstring 'lsp-hover'
    map global help-and-hovers d ': go-doc-info<ret>' -docstring 'go-doc-info'
    map global help-and-hovers h ': lsp-hover<ret>' -docstring 'lsp-hover'
    map global help-and-hovers i ': lsp-signature-help<ret>' -docstring 'lsp-signature-help'
    map global help-and-hovers r ': lsp-highlight-references<ret>' -docstring 'lsp-highlight-references'
    map global user h '<esc>: enter-user-mode help-and-hovers<ret>' -docstring 'help and hovers'
    # map global gotodef d '<esc>:lsp-definition<ret>' -docstring 'lsp-definition'
    # map global gotodef j '<esc>:go-jump<ret>' -docstring 'go-jump'
    # map global goto d '<esc>:enter-user-mode gotodef<ret>' -docstring 'gotodef mode'
}
filetype-hook c|cpp %{
    clang-enable-autocomplete; clang-enable-diagnostics
    alias window lint clang-parse
    alias window lint-next-error clang-diagnostics-next
}
# filetype-hook markdown %{
#     set window static_words %sh{tr '\n' ':' < /usr/share/dict/words}
# }

hook global BufWritePost .*\.go %{ format }

# Highlight any files whose names start with "zsh" as sh
hook global BufCreate (.*/)?\.?zsh.* %{
    set-option buffer filetype sh
}

# Highlight files ending in .conf as ini
# (Will probably be close enough)
hook global BufCreate .*\.conf %{
    set-option buffer filetype ini
}

# escape hatch
# https://github.com/mawww/kakoune/wiki/Avoid-the-escape-key
hook global InsertChar \. %{ try %{
    exec -draft hH <a-k>,\.<ret> d
    exec <esc>
    #write
}}

## Maps.
map global normal <,> ': enter-user-mode buffers<ret>'
map global normal <%> '<c-s>%' # Save position before %
map global normal <x> <a-x>
map global normal <a-x> gi<a-l>
# map global normal u l
# map global normal U L
# map global normal l u
# map global normal L U
# map global goto u l -docstring 'lide end'
map global normal <minus> ': filetree<ret>'

# Mark.kak
map global user m ': mark-word<ret>' -docstring 'mark word'
map global user M ': mark-clear<ret>' -docstring 'mark clear'

# fzf.kak
# set-option global fzf_file_command 'fd --type f --follow'
set-option global fzf_file_command 'fd'
set-option global fzf_tmux_height 22
map global normal <c-p> ': fzf-mode<ret>'

# map global normal <ret> :w<ret>
map global user <s> ': w<ret>' -docstring 'save'

# https://github.com/mawww/kakoune/issues/1791
map global object q Q -docstring 'double quote string'
map global object Q q -docstring 'single quote string'
map global view u t -docstring 'same as t'

# space is my leader
map global user <space> <space> -docstring 'remove selections except main'
map global normal <space> ,
# map global normal <backspace> <space> -docstring 'remove all sels except main'
# map global normal <a-backspace> <a-space> -docstring 'remove main sel'

# vim old habits
map global normal D '<a-l>d' -docstring 'delete to end of line'
map global normal Y '<a-l>y' -docstring 'yank to end of line'
map global normal = :format<ret> -docstring 'format buffer'

map global normal '#' :comment-line<ret> -docstring 'comment line'
map global normal '<a-#>' :comment-block<ret> -docstring 'comment block'

def -hidden slice-by-camel %{
  exec s[A-Z][a-z]+|[A-Z]+|[a-z]+<ret>
}

map global normal <c-w> ': slice-by-camel<ret>'

# Insert mode
#map global insert <c-s> <c-o>    ; # silent: stop completion
#map global insert <c-c> <c-x>    ; # complete here
#map global insert <c-k> <c-v>    ; # raw insert, use vim binding
#map global insert <c-c> <a-\;>   ; # execute one normal kak command
#map global insert <c-y> '<c-r>"' ; # paste from normal yank register, readline key
map global insert <c-y> '<a-;>!pbpaste<ret>'
# map global sysclipboard y '<a-|>pbcopy<ret>; :echo "copied selection to system clipboard"<ret>' -docstring 'yank'
# map global sysclipboard p '!pbpaste<ret>' -docstring 'paste'

# user maps
map global user S '*%s<c-/><ret>' -docstring 'select all'
map global user R ':e!<ret>' -docstring 'Reload buffer'

map global user g       -docstring 'git'                     ': enter-user-mode git<ret>'
map global user *       -docstring 'sysclipboard'            ': enter-user-mode sysclipboard<ret>'
map global user <plus>  -docstring 'switch to [+] buffer'    ': switch-to-modified-buffer<ret>'
# Format using fmt
map -docstring format global user q '|fmt -w 80<ret>: echo -markup {green}[sel] | fmt -w 80<ret>'

# map global user k ':edit-kakrc<ret>' -docstring 'edit kakrc'
#map global user c <a-s>:comment-line<ret> -docstring 'comment line'

map global normal <backspace>     ": phantom-sel-add-selection<ret>"
map global normal <a-backspace>   ": phantom-sel-select-all; phantom-sel-clear<ret>"
map global user <}>               ": phantom-sel-iterate-next<ret>" -docstring 'phantom-sel n'
map global user <{>               ": phantom-sel-iterate-prev<ret>" -docstring 'phantom-sel p'

declare-user-mode sysclipboard
map global sysclipboard i ':clipboard-import<ret>' -docstring 'import'
map global sysclipboard e ':clipboard-export<ret>' -docstring 'export'

# https://github.com/alyssais/dotfiles/blob/master/.config/kak/kakrc#L30-L38
define-command -docstring "import from the system clipboard" clipboard-import %{
  set-register dquote %sh{pbpaste}
  echo -markup "{Information}imported system clipboard to register """
}

define-command -docstring "export to the system clipboard" clipboard-export %{
  nop %sh{ printf "%s" "$kak_main_reg_dquote" | pbcopy }
  echo -markup "{Information}exported register "" to system clipboard"
}

define-command switch-to-modified-buffer %{
  eval -save-regs a %{
    reg a ''
    try %{
      eval -buffer * %{
        eval %sh{[ "$kak_modified" = true ] && echo "reg a %{$kak_bufname}; fail"}
      }
    }
    eval %sh{[ -z "$kak_main_reg_a" ] && echo "fail 'No modified buffers!'"}
    buffer %reg{a}
  }
}

# Git extras.
def git-show-blamed-commit %{
  git show %sh{git blame -L "$kak_cursor_line,$kak_cursor_line" "$kak_buffile" | awk '{print $1}'}
}
def git-log-lines %{
  git log -L %sh{
    anchor="${kak_selection_desc%,*}"
    anchor_line="${anchor%.*}"
    echo "$anchor_line,$kak_cursor_line:$kak_buffile"
  }
}
def git-toggle-blame %{
  try %{
    addhl window/git-blame group
    rmhl window/git-blame
    git blame
  } catch %{
    git hide-blame
  }
}
def git-hide-diff %{ rmhl window/git-diff }

declare-user-mode git
map global git b ': git-toggle-blame<ret>'       -docstring 'blame (toggle)'
map global git l ': git log<ret>'                -docstring 'log'
map global git c ': git commit<ret>'             -docstring 'commit'
map global git d ': git diff<ret>'               -docstring 'diff'
map global git s ': git status<ret>'             -docstring 'status'
map global git h ': git show-diff<ret>'          -docstring 'show diff'
map global git H ': git-hide-diff<ret>'          -docstring 'hide diff'
map global git w ': git-show-blamed-commit<ret>' -docstring 'show blamed commit'
map global git L ': git-log-lines<ret>'          -docstring 'log blame'

# Tab completion.
def tab-completion-enable %{
  hook -group tab-completion window InsertCompletionShow .* %{
    try %{
      exec -draft 'h<a-K>\s<ret>'
      map window insert <tab> <c-n>
      map window insert <s-tab> <c-p>
    }
  }
  hook -group tab-completion window InsertCompletionHide .* %{
    unmap window insert <tab> <c-n>
    unmap window insert <s-tab> <c-p>
  }
}
def tab-completion-disable %{ rmhooks window tab-completion }

# smarttab.kak?
# Emulate expandtab smarttab, kind of.
# Due to #2122 this can only be done as a hook, not a map.
def smarttab-enable %{
  hook -group smarttab window InsertChar \t %{ exec -draft -itersel "h%opt{indentwidth}@" }
  hook -group smarttab window InsertDelete ' ' %{
    eval -draft -itersel %{ try %{
      exec 'hGh' "s\A((.{%opt{indentwidth}})*[^ ]*) *\z<ret>" '"1R'
    }}
  }
}
def smarttab-disable %{ rmhooks window smarttab }

# Highlight trailing whitespace in normal mode, with the TrailingWhitespace face.
# What I really want is to only not highlight trailing whitespace as I'm
# inserting it, but that doesn't seem possible right now.
def show-trailing-whitespace-enable %{
  addhl window/TrailingWhitespace regex \h+$ 0:TrailingWhitespaceActive
  face window TrailingWhitespaceActive TrailingWhitespace
  hook -group trailing-whitespace window ModeChange 'normal:insert' \
    %{ face window TrailingWhitespaceActive '' }
  hook -group trailing-whitespace window ModeChange 'insert:normal' \
    %{ face window TrailingWhitespaceActive TrailingWhitespace }
}
def show-trailing-whitespace-disable %{
  rmhl window/TrailingWhitespace
  rmhooks window trailing-whitespace
}
face global TrailingWhitespace ''

# search-highlighting.kak, simplified
def search-highlighting-enable %{
  hook window -group search-highlighting NormalKey [/?*nN]|<a-[/?*nN]> %{ try %{
    addhl window/SearchHighlighting dynregex '%reg{/}' 0:Search
  }}
  hook window -group search-highlighting NormalKey <esc> %{ rmhl window/SearchHighlighting }
}
def search-highlighting-disable %{
  rmhl window/SearchHighlighting
  rmhooks window search-highlighting
}

# by lenormf, see https://github.com/mawww/kakoune/issues/1192
# decl -hidden range-specs show_matching_range
#
# hook global -group kakrc InsertChar [[(<{}>)\]] %{ eval -draft %{
#     try %{
#         exec -no-hooks <esc>\;hm<a-k>..<ret>\;
#         set window show_matching_range "%val{timestamp}:%val{selection_desc}|MatchingChar"
#     }
#
#     hook window -group once-matching InsertChar [^[(<{}>)\]] %{
#         set window show_matching_range ""
#         remove-hooks window once-matching
#     }
#
#     hook window -group once-matching InsertEnd .* %{
#         set window show_matching_range ""
#         remove-hooks window once-matching
#     }
# } }
#
# hook global -group kakrc InsertEnd .* %{
#     set buffer show_matching_range ""
# }
#
# hook global -group kakrc WinCreate .* %{
#     addhl window ranges show_matching_range
# }
