evaluate-commands %sh{
    config_files="
        common.kak
        commands.kak
        languages.kak
        tmux.kak
        plugins.kak
    "

    for file in $config_files; do
        printf "%s\n" "try %{
            source '$HOME/.config/kak/$file'
        } catch %{
            try %{ echo -debug \"%val{error}\" } catch %{ echo -debug 'Error sourcing $file' }
        }"
    done
}

